execute if score @s bb.cs.color matches 0 run loot spawn ~ ~ ~ loot boomber:carpet_on_stairs/item/white_carpet
execute if score @s bb.cs.color matches 1 run loot spawn ~ ~ ~ loot boomber:carpet_on_stairs/item/orange_carpet
execute if score @s bb.cs.color matches 2 run loot spawn ~ ~ ~ loot boomber:carpet_on_stairs/item/magenta_carpet
execute if score @s bb.cs.color matches 3 run loot spawn ~ ~ ~ loot boomber:carpet_on_stairs/item/light_blue_carpet
execute if score @s bb.cs.color matches 4 run loot spawn ~ ~ ~ loot boomber:carpet_on_stairs/item/yellow_carpet
execute if score @s bb.cs.color matches 5 run loot spawn ~ ~ ~ loot boomber:carpet_on_stairs/item/lime_carpet
execute if score @s bb.cs.color matches 6 run loot spawn ~ ~ ~ loot boomber:carpet_on_stairs/item/pink_carpet
execute if score @s bb.cs.color matches 7 run loot spawn ~ ~ ~ loot boomber:carpet_on_stairs/item/gray_carpet
execute if score @s bb.cs.color matches 8 run loot spawn ~ ~ ~ loot boomber:carpet_on_stairs/item/light_gray_carpet
execute if score @s bb.cs.color matches 9 run loot spawn ~ ~ ~ loot boomber:carpet_on_stairs/item/cyan_carpet
execute if score @s bb.cs.color matches 10 run loot spawn ~ ~ ~ loot boomber:carpet_on_stairs/item/purple_carpet
execute if score @s bb.cs.color matches 11 run loot spawn ~ ~ ~ loot boomber:carpet_on_stairs/item/blue_carpet
execute if score @s bb.cs.color matches 12 run loot spawn ~ ~ ~ loot boomber:carpet_on_stairs/item/brown_carpet
execute if score @s bb.cs.color matches 13 run loot spawn ~ ~ ~ loot boomber:carpet_on_stairs/item/green_carpet
execute if score @s bb.cs.color matches 14 run loot spawn ~ ~ ~ loot boomber:carpet_on_stairs/item/red_carpet
execute if score @s bb.cs.color matches 15 run loot spawn ~ ~ ~ loot boomber:carpet_on_stairs/item/black_carpet